version: '3.1'

services:
  tarantool:
    container_name: jobserver_tarantool
    image: tarantool/tarantool:1
    restart: always
    volumes:
      - ./config/jobserver_config.lua:/opt/tarantool/jobserver_config.lua
      - ./etc/tarantool/jobserver.lua:/usr/share/tarantool/jobserver.lua
      - ./etc/tarantool/monitor.lua:/usr/share/tarantool/monitor.lua
      - ./etc/tarantool/jobserver_instance.lua:/opt/tarantool/jobserver_instance.lua
    command: tarantool /opt/tarantool/jobserver_instance.lua
    ports:
      - "3301:3301"
    environment:
      - TARANTOOL_USER
      - TARANTOOL_PASSWORD
      - TARANTOOL_MONITOR_HOST
      - TARANTOOL_MONITOR_PORT
  worker:
    container_name: jobserver_worker
    restart: always
    build: ./docker/worker
    image: jobserver:worker
    working_dir: /opt/jobserver
    command: vendor/bin/jobqueue run default --host tarantool --config config/jobqueue.php --executors-config config/executors.php
    volumes:
      - .:/opt/jobserver
    depends_on:
      - tarantool
