# The root route on which each incoming alert enters.
route:
  # The root route must not have any matchers as it is the entry point for
  # all alerts. It needs to have a receiver configured so alerts that do not
  # match any of the sub-routes are sent to someone.
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
        # https://api.slack.com/incoming-webhooks
      - api_url: https://hooks.slack.com/services/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
        channel: hello-ci
        username: alertmanager
