{
 "title": "JobServer",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(jobserver_default_task_total,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobserver_default_task_buried{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Delayed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobserver_default_task_delayed{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobserver_default_task_total{instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jobserver_default_task_done{instance=\"$server\"}"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jobserver_default_task_ready{instance=\"$server\"}",
     "legendFormat": "Pending"
    },
    {
     "expr": "jobserver_default_task_taken{instance=\"$server\"}",
     "legendFormat": "Taken"
    }
   ]
  }
 ]
}